In [ ]:
#LAB -- 5
#Eigenvalue
import numpy as np
from numpy.linalg import qr
a = np.array([[0, 2,3], 
              [2, 3,5],
              [3 ,4,5]])

p = [1, 5, 10, 20,30]
for i in range(30):
    q, r = qr(a)
    a = np.dot(r, q)
    if i+1 in p:
        print(f'Iteration {i+1}:')
        print(a)
#Eigenvector corresponding to maximum eigenvalue
import numpy as np
def normalize(x):
    fac = abs(x).max()
    x_n = x / x.max()
    return fac, x_n
x = np.array([1, 1,1])
a = np.array([[0, 2,3], 
              [2, 3,5],
              [3 ,4,5]])

for i in range(8):
    x = np.dot(a, x)
    lambda_1, x = normalize(x)
    
print('Eigenvalue:', lambda_1)
print('Eigenvector:', x)

#Eigenvector corresponding to minimum eigenvalue
from numpy.linalg import inv
a_inv = inv(a)

for i in range(8):
    x = np.dot(a_inv, x)
    lambda_1, x = normalize(x)
    
print('Eigenvalue:', lambda_1)
print('Eigenvector:', x)


Iteration 1:
[[ 8.53846154 -3.61363945 -0.19048483]
 [-3.75100002 -0.01015965  0.07326229]
 [ 0.80003628  0.07326229 -0.52830189]]
Iteration 5:
[[ 9.89139701e+00  4.83448514e-01 -8.05614047e-01]
 [-1.70807615e-03 -1.37991119e+00 -3.34245572e-01]
 [ 5.73684428e-06  5.75420311e-03 -5.11485813e-01]]
Iteration 10:
[[ 9.89132336e+00  4.90459322e-01  8.02350924e-01]
 [ 8.96249054e-08 -1.37763286e+00  3.40080374e-01]
 [ 2.16201094e-12 -4.12734342e-05 -5.13690497e-01]]
Iteration 20:
[[ 9.89132336e+00  4.90497562e-01  8.02327496e-01]
 [ 2.46134495e-16 -1.37761662e+00  3.40121639e-01]
 [ 3.08644398e-25 -2.14547383e-09 -5.13706744e-01]]
Iteration 30:
[[ 9.89132336e+00  4.90497564e-01  8.02327495e-01]
 [ 6.75946324e-25 -1.37761662e+00  3.40121641e-01]
 [ 4.40622912e-38 -1.11530120e-13 -5.13706744e-01]]
Eigenvalue: 9.891320757684891
Eigenvector: [0.47805354 0.86429078 1.        ]
Eigenvalue: 0.08333339306853582
Eigenvector: [0.99999915 1.         0.99999879]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
#Important libraries to import
import numpy as np
import pandas as pd
from sklearn import datasets
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression,LinearRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

In [ ]:
# LAB 6 - I
# Download the data from the given link https://www.kaggle.com/datasets/priy998/golf-play-dataset?select=golf_df.csv
!pip install chefboost
golf_dataset = pd.read_csv('/content/golf_df.csv') 
from chefboost import Chefboost as chef
config = {'algorithm': 'C4.5'}
model = chef.fit(golf_dataset, config = config, target_label = 'Play')

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
[INFO]:  1 CPU cores will be allocated in parallel running
C4.5  tree is going to be built...
-------------------------
finished in  0.9708230495452881  seconds
-------------------------
Evaluate  train set
-------------------------
Accuracy:  100.0 % on  14  instances
Labels:  ['no' 'yes']
Confusion matrix:  [[5, 0], [0, 9]]
Precision:  100.0 %, Recall:  100.0 %, F1:  100.0 %


In [ ]:
#LAB_6 -- II
wine_dataset  = datasets.load_wine()
wine_x = wine_dataset.data
wine_y = wine_dataset.target
wine_x_train,wine_x_test,wine_y_train,wine_y_test = train_test_split(wine_x,wine_y,test_size = 0.3)

decision_tree_clf = DecisionTreeClassifier(criterion = 'entropy') # As id3 tree algorithm use entropy for loss calculation
decision_tree_clf.fit(wine_x_train,wine_y_train)

print(f"ID3 Accuracy for Wine Dataset : {accuracy_score(wine_y_test,decision_tree_clf.predict(wine_x_test))*100}%")
print(f"ID3 Classification Report: \n{classification_report(wine_y_test, decision_tree_clf.predict(wine_x_test))}")

ID3 Accuracy for Wine Dataset : 92.5925925925926%
ID3 Classification Report: 
              precision    recall  f1-score   support

           0       0.89      0.94      0.91        17
           1       0.89      0.89      0.89        18
           2       1.00      0.95      0.97        19

    accuracy                           0.93        54
   macro avg       0.93      0.93      0.93        54
weighted avg       0.93      0.93      0.93        54



In [ ]:
#LAB 7 
#Download the datset from this link - - https://www.kaggle.com/datasets/devvret/congressional-voting-records?select=house-votes-84.csv
df = pd.read_csv('/content/house-votes-84.csv')## Upload the datsets into colab and copy the path

house_votes_x = df.drop(['Class Name'],axis = 1)
house_votes_y=  df['Class Name']

for col in house_votes_x.columns:
    house_votes_x[col] = [1 if vote == 'y' else 0 for vote in house_votes_x[col]]
house_votes_y = [1 if vote == 'republican' else 0 for vote in house_votes_y]
house_votes_x_train,house_votes_x_test,house_votes_y_train,house_votes_y_test = train_test_split(house_votes_x,house_votes_y,test_size = 0.3)

naive_bayes_classifier= GaussianNB().fit(house_votes_x_train,house_votes_y_train)
print(f"Naive Bayes Accuracy for Wine Dataset : {accuracy_score(house_votes_y_test,naive_bayes_classifier.predict(house_votes_x_test))*100}%")
print(f"Naive Bayes Classification Report: \n{classification_report(house_votes_y_test,naive_bayes_classifier.predict(house_votes_x_test))}")

Naive Bayes Accuracy for Wine Dataset : 93.89312977099237%
Naive Bayes Classification Report: 
              precision    recall  f1-score   support

           0       0.92      0.97      0.94        69
           1       0.97      0.90      0.93        62

    accuracy                           0.94       131
   macro avg       0.94      0.94      0.94       131
weighted avg       0.94      0.94      0.94       131



In [ ]:
#LAB -- 8
iris = datasets.load_iris()
iris_data_x = iris.data
iris_data_y = iris.target

iris_data_x_train,iris_data_x_test,iris_data_y_train,iris_data_y_test = train_test_split(iris_data_x,iris_data_y,test_size = 0.3)
KNN_Clf = KNeighborsClassifier().fit(iris_data_x_train,iris_data_y_train)
print(f"K-Nearest Neighbors classifier Accuracy for Wine Dataset : {accuracy_score(iris_data_y_test,KNN_Clf.predict(iris_data_x_test))*100}%")
print(f"K-Nearest Neighbors classifier Classification Report: \n{classification_report(iris_data_y_test,KNN_Clf.predict(iris_data_x_test))}")

K-Nearest Neighbors classifier Accuracy for Wine Dataset : 95.55555555555556%
K-Nearest Neighbors classifier Classification Report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        16
           1       0.88      1.00      0.94        15
           2       1.00      0.86      0.92        14

    accuracy                           0.96        45
   macro avg       0.96      0.95      0.95        45
weighted avg       0.96      0.96      0.96        45



In [ ]:
#LAB -- 9
url ='https://archive.ics.uci.edu/ml/machine-learning-databases/parkinsons/parkinsons.data' # data for lab 9
data = pd.read_csv(url)

parkinson_data_x  = data.drop(['status','name'],axis=1)
parkinson_data_y = data['status']

parkinson_data_x_train ,parkinson_data_x_test, parkinson_data_y_train ,parkinson_data_y_test= train_test_split(parkinson_data_x,parkinson_data_y,test_size  = 0.3)
svm_clf = SVC().fit(parkinson_data_x_train,parkinson_data_y_train)
print(f"Support Vector Classifier Accuracy for Wine Dataset : {accuracy_score(parkinson_data_y_test,svm_clf.predict(parkinson_data_x_test))*100}%")
print(f"Support Vector Classifier Classification Report: \n{classification_report(parkinson_data_y_test,svm_clf.predict(parkinson_data_x_test))}")

Support Vector Classifier Accuracy for Wine Dataset : 71.1864406779661%
Support Vector Classifier Classification Report: 
              precision    recall  f1-score   support

           0       1.00      0.11      0.19        19
           1       0.70      1.00      0.82        40

    accuracy                           0.71        59
   macro avg       0.85      0.55      0.51        59
weighted avg       0.80      0.71      0.62        59



In [ ]:
#LAB -- 10
from sklearn.model_selection import train_test_split
x= iris.data
y = iris.target
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3)


from sklearn import svm
clf = svm.SVC()
clf.fit(x_train, y_train)
y_pred_svm = clf.predict(x_test)
clf.support_vectors_
print(f"SVM Classification Report: \n{classification_report(y_test, y_pred_svm)}")

import numpy as np
from sklearn.neighbors import KNeighborsClassifier
knn  = KNeighborsClassifier()


knn  = knn.fit(x_train,y_train)
y_pred_knn = knn.predict(x_test)
print(f"KNN Classification Report: \n{classification_report(y_test, y_pred_knn)}")

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

id3 = DecisionTreeClassifier(criterion='entropy')
id3.fit(x_train, y_train)
y_pred_id3 = id3.predict(x_test)
accuracy_id3 = accuracy_score(y_test, y_pred_id3)
print(f"ID3 Accuracy: {accuracy_id3}")
print(f"ID3 Classification Report: \n{classification_report(y_test, y_pred_id3)}")

ID3 Classification Report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       0.94      1.00      0.97        16
           2       1.00      0.93      0.96        14

    accuracy                           0.98        45
   macro avg       0.98      0.98      0.98        45
weighted avg       0.98      0.98      0.98        45

ID3 Classification Report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1       1.00      1.00      1.00        16
           2       1.00      1.00      1.00        14

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

ID3 Accuracy: 0.9555555555555556
ID3 Classification Report: 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        15
           1

In [ ]:
#LAB -- 12
import numpy as np
import pandas as pd
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

# Step 1: Prepare the data
california_data = fetch_california_housing()
X = california_data.data
y = california_data.target.reshape(-1, 1)
scaler = StandardScaler()
X = scaler.fit_transform(X)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Step 2: Initialize the network
input_size = X_train.shape[1]
hidden_size = 32
output_size = 1
weights1 = np.random.randn(input_size, hidden_size) / np.sqrt(input_size)
weights2 = np.random.randn(hidden_size, output_size) / np.sqrt(hidden_size)

# Step 3: Forward pass
def forward(X):
    hidden_layer = np.dot(X, weights1)
    hidden_layer = np.maximum(hidden_layer, 0)
    output_layer = np.dot(hidden_layer, weights2)
    return output_layer

# Step 4: Calculate error
def mse_loss(y_true, y_pred):
    return np.mean(np.square(y_true - y_pred))

# Step 5: Backward pass
def backward(X, y_true, y_pred, hidden_layer):
    output_error = y_pred - y_true
    output_delta = output_error / X.shape[0]
    hidden_error = np.dot(output_delta, weights2.T)
    hidden_delta = hidden_error * (hidden_layer > 0)
    weights2_update = np.dot(hidden_layer.T, output_delta)
    weights1_update = np.dot(X.T, hidden_delta)
    return weights1_update, weights2_update

# Step 6: Train the network
learning_rate = 0.01
epochs = 1000
for epoch in range(epochs):
    # Forward pass
    hidden_layer = np.dot(X_train, weights1)
    hidden_layer = np.maximum(hidden_layer, 0)
    output_layer = np.dot(hidden_layer, weights2)
   
    # Calculate loss
    loss = mse_loss(y_train, output_layer)
   
    # Backward pass
    weights1_update, weights2_update = backward(X_train, y_train, output_layer, hidden_layer)
    weights1 -= learning_rate * weights1_update
    weights2 -= learning_rate * weights2_update
   
    # Print progress
    if epoch % 100 == 0:
        print(f"Epoch {epoch}: Loss = {loss:.4f}")
   
# Step 7: Evaluate the network
y_pred = forward(X_test)
rmse = np.sqrt(mse_loss(y_test, y_pred))
print(f"RMSE = {rmse:.4f}")

Epoch 0: Loss = 5.9958
Epoch 100: Loss = 1.0898
Epoch 200: Loss = 0.9484
Epoch 300: Loss = 0.9010
Epoch 400: Loss = 0.8674
Epoch 500: Loss = 0.8408
Epoch 600: Loss = 0.8186
Epoch 700: Loss = 0.7999
Epoch 800: Loss = 0.7838
Epoch 900: Loss = 0.7698
RMSE = 0.8876


In [ ]:
#LAB -- 13
import numpy as np
# defining the data points
data = np.array([[2, 10], [2, 5], [8, 4], [5, 8], [7, 5], [6, 4], [1, 2], [4, 9]])
# defining the initial cluster centers
centers = np.array([[2, 10], [5, 8], [1, 2]])
# defining the number of clusters
K = 3
# defining the maximum number of iterations
max_iters = 10
# defining the Euclidean distance function
def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2) ** 2))
# k-means clustering algorithm
for i in range(max_iters):
    # initializing empty clusters
    clusters = [[] for _ in range(K)]
    # assigning data points to the closest cluster center
    for point in data:
        distances = [euclidean_distance(point, center) for center in centers]
        closest_center = np.argmin(distances)
        clusters[closest_center].append(point)
# updating the cluster centers
for j in range(K):
    centers[j] = np.mean(clusters[j], axis=0)
# printing the cluster centers after the first round of execution
if i == 0:
    print("Cluster centers after the first round of execution:")
    print(centers[i])
    print()
# printing the first three clusters
if i < 3:
    print("Cluster", i+1, ":", clusters[i])

centers,clusters
#Each line  in a cluster is a seperate cluster

(array([[ 2, 10],
        [ 6,  6],
        [ 1,  3]]),
 [[array([ 2, 10])],
  [array([8, 4]), array([5, 8]), array([7, 5]), array([6, 4]), array([4, 9])],
  [array([2, 5]), array([1, 2])]])