In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
from sklearn import datasets
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [3]:
iris=datasets.load_iris()
iris.target
X=iris.data
Y=iris.target
print('X: ',X)
print('\n\nY: ',Y)

X:  [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.

In [5]:
clf=LinearRegression()
x_train, x_test, y_train, y_test=train_test_split(X,Y,test_size=0.2,random_state=40)

In [13]:
clf.fit(x_train,y_train)
score=clf.score(x_test,y_test)
print(score)
pred=clf.predict(x_test)
print('pred: ',pred)

0.9235413296129528
pred:  [ 0.01136689  1.42180667  1.95904146  2.04922364  1.2023588   2.10825359
  1.34482093  1.2344271   1.45468214 -0.10399721  1.25017588  0.01566994
 -0.04347468  1.58139549  0.86005697  2.1294761   1.59462095  1.9002351
  1.25352809  1.27661398  1.99342586  2.00303368  1.20776896 -0.03295431
  1.06726831 -0.05882164 -0.08342184  1.71537886 -0.0769209   0.95225882]


In [11]:
print(clf.intercept_)
print(r2_score(pred,y_test))
print(clf.coef_)
print(mean_squared_error(pred,y_test))

0.3507037980744492
0.9234300875726299
[-0.16437734 -0.02705083  0.26958104  0.57310249]
0.045535385919397035
